apiVersion: v1
kind: Service
metadata:
  name: {{ include "hugs.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hugs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hugs.selectorLabels" . | nindent 4 }}
